name: Build Kernel
on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update and install packages
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt-get install -y bc bison build-essential ccache curl flex git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 python-is-python3

    - name: Clone repositories
      run: |
        git clone -b 16.0 https://github.com/crdroidandroid/android_kernel_xiaomi_sm8550.git
        git clone -b lineage-23.0 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-gnu-9.3.git
        git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b.git
        git clone -b android-16.0.0_r0.7 https://android.googlesource.com/kernel/prebuilts/build-tools build-tools
        git clone https://github.com/LineageOS/android_prebuilts_tools-lineage.git

    - name: Compile kernel
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Upload Image artifact
      uses: actions/upload-artifact@v3
      with:
        name: Image
        path: build/arch/arm64/boot/Image
